switch(argument0)
{
case 0: return "Empty Space" break;

case 1: return "Dust" break;
case 2: return "Stone" break;
case 3: return "Snow" break;
case 4: return "Concrete" break;
case 5: return "Salt" break;
case 6: return "Broken Metal" break;
case 7: return "Sand" break;
case 8: return "Broken Glass" break;
case 9: return "Yeast" break;
case 10: return "Fuse Powder" break;
case 11: return "Broken Coal" break;
case 12: return "Freeze Powder" break;
case 13: return "Gravity Dust" break;
case 14: return "Anti Air" break;
case 15: return "Powdered Quartz" break;
case 16: return "Broken Electronics" break;
case 17: return "Clay Dust" break;
case 18: return "Saw Dust" break;

case 101: return "Goo" break;
case 102: return "Ice" break;
case 103: return "Wood" break;
case 104: return "Plant" break;
case 105: return "Breakable Metal" break;
case 106: return "Wax" break;
case 107: return "Glass" break;
case 108: return "Nitrogen Ice" break;
case 109: return "Coal" break;
case 110: return "Brick" break;
case 111: return "Fuse" break;
case 112: return "Iron" break;
case 113: return "Dry Ice" break;
case 114: return "Sponge" break;
case 115: return "Rime" break;
case 116: return "Vine" break;
case 117: return "Shield" break;
case 118: return "Filter" break;
case 119: return "Quartz" break;
case 120: return "Titanium" break;
case 121: return "Gold" break;
case 122: return "Ceramic" break;
case 123: return "Rapid Heat Conductor" break;

case 201: return "Water" break;
case 202: return "Oil" break;
case 203: return "Lava" break;
case 204: return "Acid" break;
case 205: return "Distilled Water" break;
case 206: return "Saltwater" break;
case 207: return "Melted Wax" break;
case 208: return "Liquid Nitrogen" break;
case 209: return "Diesel" break;
case 210: return "Liquid Oxygen" break;
case 211: return "Glow" break;
case 212: return "Carbonated Water" break;
case 213: return "Bizzare" break;
case 214: return "Paste" break;
case 215: return "Gel" break;
case 216: return "Soap" break;
case 217: return "Virus" break;

case 301: return "Fire" break;
case 302: return "Gunpowder" break;
case 303: return "Nitroglycerine" break;
case 304: return "C-4" break;
case 305: return "Rubidium" break;
case 306: return "Liquid Rubidium" break;
case 307: return "Lightning" break;
case 308: return "Thermite" break;
case 309: return "Cold Flame" break;
case 310: return "Fireworks" break;
case 311: return "Lightning" break;
case 312: return "More Destructive Bomb" break;
case 313: return "Old Fireworks" break;
case 314: return "Bomb" break;
case 315: return "Cold Explosive" break;
case 316: return "TNT" break;
case 317: return "Ignition Cord" break;

case 901: return "Game of Life" break;
case 902: return "High Life" break;
case 903: return "Assimilation" break;
case 904: return "2X2" break;
case 905: return "Day and Night" break;
case 906: return "Amoeba" break;
case 907: return "Move" break;
case 908: return "Pseudo Life" break;
case 909: return "Diamoeba" break;
case 910: return "34" break;
case 911: return "Long Life" break;
case 912: return "Stains" break;
case 913: return "Seeds" break;
case 914: return "Maze" break;
case 915: return "Coagulations" break;
case 916: return "Walled Cities" break;
case 917: return "Gnarl" break;
case 918: return "Replicator" break;
case 919: return "Mystery" break;
case 920: return "Star Wars" break;
case 921: return "Living on the Edge" break;
case 922: return "Brian 6" break;
case 923: return "Frogs" break;
case 924: return "Frogs 2" break;
}
